# Site
repository: andreapava/andreapava.github.io.git
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Andrea Pavin
title: iOS Developer
email: pavinandrea5@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Andrea and I'm a <mark>iOS</mark> developer. As well as creating apps from the ground up I also have experience making software and web apps.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#       additional_links:
#         - title:  sproogen/modern-resume-theme
#           icon: fab fa-github
#           url: github.com/sproogen/modern-resume-theme
#         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#         #   icon: fab fa-github
#         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#       quote: >
#         //TODO
#       description: | # this will include new lines to allow paragraphs
#           //TODO
#               //TODO

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Zero12
        link: zero12.it
        # link_text: http://www.zero12.it/
        sub_title: iOS Developer
        caption: January 2020 - Present
        description: | # this will include new lines to allow paragraphs
            - ##Retail app |
                  dfdfdfdf
            - ##Retail app 
                | dfdfdfdf
            - | # ##IoT app
            - | Brand sustainability app
                ------------------------
            - **Office access control and rooms/desks booking app**
            - | # **Real-time Joint and body position processing**

  - title: Key skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Swift
      - SwiftUI
      - iOS SDK
      - 3rd party SDKs and API(S) integration
      - AWS Certified Cloud Practitioner
      - Collaboration
      - Communication
      - Organizational skills

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Padua
        sub_title: BSc Computer Science
        quote: >
          Universa Universis Patavina Libertas
#        description: | # this will include new lines to allow paragraphs
#          //TODO: university experiences

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my IT interests some of my other interests and hobbies are:
      - Music
      - Cinema
      - Books
      - Motorcycles
      - Gym/Powerlifting  
      - Gaming
      - Hi-Fi Systems
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
