# Site
repository: andreapava/andreapava.github.io.git
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Andrea Pavin
title: iOS Developer
email: pavinandrea5@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Andrea and I'm an iOS developer.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#       additional_links:
#         - title:  sproogen/modern-resume-theme
#           icon: fab fa-github
#           url: github.com/sproogen/modern-resume-theme
#         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#         #   icon: fab fa-github
#         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#       quote: >
#         //TODO
#       description: | # this will include new lines to allow paragraphs
#           //TODO
#               //TODO

  - title: Experience # Title for the section
    layout: text # Type of content section (list/text)
    content:
      - layout: left
        title: Zero12
        link: zero12.it
        # link_text: http://www.zero12.it/
        sub_title: iOS Developer
        caption: 2020 - 2022
        description: | # this will include new lines to allow paragraphs
      - layout: left
        title: Lenis
        link: https://lenis.tech/
        # link_text: http://www.zero12.it/
        sub_title: iOS Developer
        caption: 2022 - Present
        description: | # this will include new lines to allow paragraphs

  - title: Indie development # Title for the section
    layout: text # Type of content section (list/text)
    content:
      - layout: left
        title: FastGymLogs
        link: zero12.it
        
#- IoT stove control 
#  -----------------
# >
# The app can remotely control and monitor multiple stoves using BLE and MQTT.
#  Heavy use of Modbus communication protocol and RxSwift.
#- Joint position based photo shooting 
#  -----------------
# >
# The app can recognize body positions in real-time and take pictures based on the user joints configuration. 
#- Brand sustainability
#  --------------------
# >
# The app displays products lists and details regarding the product's sustainability of the brand.
# Implemented SSO authentication to display additional data and let the user participate in sustainability quizzes.
# Implemented custom animated charts.


  - title: Key skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - UIKit
      - SwiftUI
      - 3rd party SDKs and API(S) integration
      - Collaboration
      - Communication
      - Organizational skills
      - Somehow also AWS Certified Cloud Practitioner

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Padua
        sub_title: BSc Computer Science
        quote: >
          Universa Universis Patavina Libertas
#        description: | # this will include new lines to allow paragraphs
#          //TODO: university experiences

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my IT interests some of my other interests and hobbies are:
#      - Music
#      - Cinema
#      - Books
#      - Motorcycles
#      - Gym/Powerlifting  
#      - Gaming
#      - Hi-Fi Systems
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
